export const excuses = {
  en: [
    "I need to focus on my relationship with my houseplants - they're going through a rough patch.",
    "My horoscope said Mercury is in microwave, and dating during this time brings bad luck.",
    "I've decided to become a professional Netflix critic and need to maintain my objectivity.",
    "My pet goldfish is having an existential crisis and needs my full attention.",
    "I'm training to become a professional sleeper and relationships interfere with my REM cycles.",
    "I've joined a secret society of people who collect vintage spoons, and you wouldn't understand.",
    "My imaginary friend is jealous of our relationship and threatened to leave me.",
    "I need to dedicate my life to finding the perfect pizza topping combination.",
    "I'm allergic to commitment - my doctor says it gives me emotional hives.",
    "I've decided to become fluent in dolphin language and it requires complete social isolation.",
    "My shadow has been acting weird lately and I need to figure out what's wrong.",
    "I'm on a spiritual journey to find the meaning of why socks disappear in the dryer.",
    "I've been chosen by aliens to document human dating rituals, and dating you would compromise my research.",
    "My grandmother's ghost appeared and said you're not 'the one' - and she's never wrong.",
    "I need to focus on my career as a professional cloud watcher.",
    "I'm writing a book about why relationships don't work, and I need more material.",
    "My therapist says I have commitment issues, but I'm not committed to fixing them.",
    "I've decided to marry my WiFi router - it's the most stable relationship I've ever had.",
    "I'm training to become a hermit and you're too social for my new lifestyle.",
    "My lucky socks told me we're not compatible - and I always trust my socks.",
    "I need to focus on my relationship with gravity - we've been drifting apart.",
    "I've been recruited by squirrels to be their human ambassador.",
    "My coffee maker and I are in couples therapy, and I can't handle two relationships right now.",
    "I'm allergic to the letter 'L' in 'love' - it makes me break out in panic.",
    "I've decided to become a professional procrastinator and I'll get back to you... eventually.",
  ],
  fr: [
    "Je dois me concentrer sur ma relation avec mes plantes d'intérieur - elles traversent une période difficile.",
    "Mon horoscope dit que Mercure est dans le micro-ondes, et sortir ensemble pendant cette période porte malheur.",
    "J'ai décidé de devenir critique professionnel de Netflix et je dois maintenir mon objectivité.",
    "Mon poisson rouge traverse une crise existentielle et a besoin de toute mon attention.",
    "Je m'entraîne pour devenir dormeur professionnel et les relations interfèrent avec mes cycles REM.",
    "J'ai rejoint une société secrète de collectionneurs de cuillères vintage, tu ne comprendrais pas.",
    "Mon ami imaginaire est jaloux de notre relation et a menacé de me quitter.",
    "Je dois consacrer ma vie à trouver la combinaison parfaite de garnitures de pizza.",
    "Je suis allergique à l'engagement - mon médecin dit que ça me donne de l'urticaire émotionnel.",
    "J'ai décidé d'apprendre couramment le langage des dauphins et ça nécessite un isolement social complet.",
    "Mon ombre agit bizarrement dernièrement et je dois comprendre ce qui ne va pas.",
    "Je suis en voyage spirituel pour comprendre pourquoi les chaussettes disparaissent dans le sèche-linge.",
    "J'ai été choisi par des extraterrestres pour documenter les rituels de séduction humains, et sortir avec toi compromettrait mes recherches.",
    "Le fantôme de ma grand-mère est apparu et a dit que tu n'es pas 'le bon' - et elle ne se trompe jamais.",
    "Je dois me concentrer sur ma carrière d'observateur professionnel de nuages.",
    "J'écris un livre sur pourquoi les relations ne marchent pas, et j'ai besoin de plus de matériel.",
    "Mon thérapeute dit que j'ai des problèmes d'engagement, mais je ne suis pas engagé à les résoudre.",
    "J'ai décidé d'épouser mon routeur WiFi - c'est la relation la plus stable que j'aie jamais eue.",
    "Je m'entraîne pour devenir ermite et tu es trop social pour mon nouveau style de vie.",
    "Mes chaussettes porte-bonheur m'ont dit qu'on n'était pas compatibles - et je fais toujours confiance à mes chaussettes.",
    "Je dois me concentrer sur ma relation avec la gravité - on s'éloigne l'un de l'autre.",
    "J'ai été recruté par des écureuils pour être leur ambassadeur humain.",
    "Ma cafetière et moi sommes en thérapie de couple, et je ne peux pas gérer deux relations en même temps.",
    "Je suis allergique à la lettre 'A' dans 'amour' - ça me donne des crises de panique.",
    "J'ai décidé de devenir procrastinateur professionnel et je te répondrai... éventuellement.",
  ],
};
